services:
  app:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - ./:/workspace:cached
      - codex_cache:/home/vscode/.cache  # キャッシュはボリュームに退避
      - ./tools/.codex:/root/.codex
    environment:
      CODEX_HOME: /workspace/tools/.codex
      # OPENAI_API_KEY: ${OPENAI_API_KEY}   # 必要なら .env から注入
    working_dir: /workspace
    command: sleep infinity           # Dev Container が attach するだけ
    init: true                        # プロセス管理を安定化
volumes:
  codex_cache: